-- CreateEnum
CREATE TYPE "PROJECT_MEMBERSHIP_STATUS" AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED');

-- AlterTable
ALTER TABLE "ProjectMembership" ADD COLUMN     "status" "PROJECT_MEMBERSHIP_STATUS" NOT NULL DEFAULT 'PENDING';
